--- 
framework: jest
postMerge: 
  pattern: 
    - ./test/IO.ts
    - ./test/Json.ts
    - ./test/Ring.ts
    - ./test/Foldable.ts
    - ./test/Date.ts
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
postRun: 
  - "npm run docs"
preMerge: 
  pattern: 
    - ./test/IO.ts
    - ./test/Json.ts
    - ./test/Ring.ts
    - ./test/Foldable.ts
    - ./test/Date.ts
preRun: 
  - "npm ci"
  - "npm run lint"
  - "npm run prettier"
  - "npm run dtslint"
  - "npm run jest-clear-cache"
